export const bannerObj = [
  {
    adult: false,
    backdrop_path: "/A4JG9mkAjOQ3XNJy2oji1Jr224R.jpg",
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    popularity: 14152.827,
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    release_date: "2024-07-24",
    title: "Deadpool & Wolverine",
    video: false,
    vote_average: 8.008,
    vote_count: 987,
  },
  {
    adult: false,
    backdrop_path: "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
    genre_ids: [28, 80, 53, 35],
    id: 573435,
    original_language: "en",
    original_title: "Bad Boys: Ride or Die",
    overview:
      "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
    popularity: 4694.756,
    poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
    release_date: "2024-06-05",
    title: "Bad Boys: Ride or Die",
    video: false,
    vote_average: 7.7,
    vote_count: 1203,
  },
  {
    adult: false,
    backdrop_path: "/5g2n3ilC8DpYv4diJeuQ1vKG2Kb.jpg",
    genre_ids: [16, 10751, 35, 28],
    id: 519182,
    original_language: "en",
    original_title: "Despicable Me 4",
    overview:
      "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    popularity: 2736.441,
    poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    release_date: "2024-06-20",
    title: "Despicable Me 4",
    video: false,
    vote_average: 7.206,
    vote_count: 475,
  },
  {
    adult: false,
    backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
    genre_ids: [28, 12, 35],
    id: 293660,
    original_language: "en",
    original_title: "Deadpool",
    overview:
      "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
    popularity: 1045.895,
    poster_path: "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
    release_date: "2016-02-09",
    title: "Deadpool",
    video: false,
    vote_average: 7.619,
    vote_count: 30330,
  },
  {
    adult: false,
    backdrop_path: "/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg",
    genre_ids: [16, 878, 28],
    id: 1209290,
    original_language: "en",
    original_title: "Justice League: Crisis on Infinite Earths Part Three",
    overview:
      "Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?",
    popularity: 1114.605,
    poster_path: "/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg",
    release_date: "2024-07-16",
    title: "Justice League: Crisis on Infinite Earths Part Three",
    video: false,
    vote_average: 7.723,
    vote_count: 110,
  },
  {
    adult: false,
    backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
    genre_ids: [28, 35],
    id: 1048241,
    original_language: "en",
    original_title: "My Spy The Eternal City",
    overview:
      "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
    popularity: 979.672,
    poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
    release_date: "2024-07-18",
    title: "My Spy The Eternal City",
    video: false,
    vote_average: 6.755,
    vote_count: 165,
  },
  {
    adult: false,
    backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    genre_ids: [878, 12, 28],
    id: 653346,
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview:
      "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
    popularity: 931.197,
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    release_date: "2024-05-08",
    title: "Kingdom of the Planet of the Apes",
    video: false,
    vote_average: 7.177,
    vote_count: 2167,
  },
  {
    adult: false,
    backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
    genre_ids: [28, 12, 878],
    id: 786892,
    original_language: "en",
    original_title: "Furiosa: A Mad Max Saga",
    overview:
      "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
    popularity: 1009.961,
    poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    release_date: "2024-05-22",
    title: "Furiosa: A Mad Max Saga",
    video: false,
    vote_average: 7.651,
    vote_count: 2398,
  },
  {
    adult: false,
    backdrop_path: "/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg",
    genre_ids: [28, 35, 12],
    id: 383498,
    original_language: "en",
    original_title: "Deadpool 2",
    overview:
      "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
    popularity: 758.63,
    poster_path: "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
    release_date: "2018-05-10",
    title: "Deadpool 2",
    video: false,
    vote_average: 7.491,
    vote_count: 17392,
  },
  {
    adult: false,
    backdrop_path: "/9Y9wTgrMk4G1YNPDDekNk7dybwx.jpg",
    genre_ids: [28, 12, 10752],
    id: 1152624,
    original_language: "en",
    original_title: "3 Days in Malay",
    overview:
      "Marines stationed at an airfield in Malay during WWII get wind of a coming raid by the Japanese. Unable to get reinforcements approved, they engage in a harrowing 3-day battle against enemy forces.",
    popularity: 785.738,
    poster_path: "/hqnfqeCILvgKGWKOut5lVdxdeJh.jpg",
    release_date: "2023-08-11",
    title: "3 Days in Malay",
    video: false,
    vote_average: 5,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/wPNI1fd18z5TKBOK9Mv9Rfjb0j0.jpg",
    genre_ids: [53, 18, 28, 80],
    id: 729165,
    original_language: "en",
    original_title: "Out of Exile",
    overview:
      "Recently paroled thief Gabriel Russell tries to balance his life and mend a troubled family as an FBI agent hunts him down, along with his crew after a botched armored car robbery.",
    popularity: 662.446,
    poster_path: "/jgF5XaXnJmOgMxulhy2k1f9LNNc.jpg",
    release_date: "2023-01-20",
    title: "Out of Exile",
    video: false,
    vote_average: 6.383,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: "/s5znBQmprDJJ553IMQfwEVlfroH.jpg",
    genre_ids: [28, 35, 10752, 18],
    id: 799583,
    original_language: "en",
    original_title: "The Ministry of Ungentlemanly Warfare",
    overview:
      "During World War II, the British Army assigns a group of competent soldiers to carry out a mission against the Nazi forces behind enemy lines... A true story about a secret British WWII organization – the Special Operations Executive. Founded by Winston Churchill, their irregular warfare against the Germans helped to change the course of the war, and gave birth to modern black operations.",
    popularity: 1168.768,
    poster_path: "/8aF0iAKH9MJMYAZdi0Slg77RYa2.jpg",
    release_date: "2024-04-18",
    title: "The Ministry of Ungentlemanly Warfare",
    video: false,
    vote_average: 7.197,
    vote_count: 611,
  },
  {
    adult: false,
    backdrop_path: "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
    genre_ids: [28, 35, 80],
    id: 280180,
    original_language: "en",
    original_title: "Beverly Hills Cop: Axel F",
    overview:
      "Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.",
    popularity: 543.672,
    poster_path: "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
    release_date: "2024-06-20",
    title: "Beverly Hills Cop: Axel F",
    video: false,
    vote_average: 6.874,
    vote_count: 754,
  },
  {
    adult: false,
    backdrop_path: "/veIyxxi5Gs8gvztLEW1Ysb8rrzs.jpg",
    genre_ids: [878, 28, 12],
    id: 823464,
    original_language: "en",
    original_title: "Godzilla x Kong: The New Empire",
    overview:
      "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    popularity: 633.845,
    poster_path: "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 7.191,
    vote_count: 3311,
  },
  {
    adult: false,
    backdrop_path: "/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg",
    genre_ids: [10752, 28, 18],
    id: 929590,
    original_language: "en",
    original_title: "Civil War",
    overview:
      "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
    popularity: 524.935,
    poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    release_date: "2024-04-10",
    title: "Civil War",
    video: false,
    vote_average: 6.978,
    vote_count: 2030,
  },
  {
    adult: false,
    backdrop_path: "/qwhnq8pkFEAFXRwmscISOKK90Mu.jpg",
    genre_ids: [28, 53],
    id: 560016,
    original_language: "en",
    original_title: "Monkey Man",
    overview:
      "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
    popularity: 462.676,
    poster_path: "/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
    release_date: "2024-04-03",
    title: "Monkey Man",
    video: false,
    vote_average: 7.036,
    vote_count: 661,
  },
  {
    adult: false,
    backdrop_path: "/iwkWvcXcP8M4r9HLglhVEhgGyVu.jpg",
    genre_ids: [28, 18, 27, 53],
    id: 1001311,
    original_language: "fr",
    original_title: "Sous la Seine",
    overview:
      "In order to save Paris from an international bloodbath, a grieving scientist is forced to face her tragic past when a giant shark appears in the Seine.",
    popularity: 450.659,
    poster_path: "/qZPLK5ktRKa3CL4sKRZtj8UlPYc.jpg",
    release_date: "2024-06-04",
    title: "Under Paris",
    video: false,
    vote_average: 6.097,
    vote_count: 968,
  },
  {
    adult: false,
    backdrop_path: "/5ZSwZPKgcTJJwhxjbOHeoBTVaKh.jpg",
    genre_ids: [35, 28, 12],
    id: 567604,
    original_language: "en",
    original_title: "Once Upon a Deadpool",
    overview:
      "A kidnapped Fred Savage is forced to endure Deadpool's PG-13 rendition of Deadpool 2 as a Princess Bride-esque story that's full of magic, wonder & zero F's.",
    popularity: 325.541,
    poster_path: "/5Ka49BWWyKMXr93YMbH5wLN7aAM.jpg",
    release_date: "2018-12-11",
    title: "Once Upon a Deadpool",
    video: false,
    vote_average: 7.093,
    vote_count: 727,
  },
  {
    adult: false,
    backdrop_path: "/gsljBGOjBkbuNt3gvIDXQWnudn.jpg",
    genre_ids: [28, 35, 80],
    id: 558144,
    original_language: "en",
    original_title: "Deadpool: No Good Deed",
    overview:
      "Deadpool sees an opportunity to save the day, but it doesn't go entirely as planned.",
    popularity: 296.578,
    poster_path: "/wlKU9yB0Q8nfPMakBcSBT0JGS7.jpg",
    release_date: "2017-03-03",
    title: "Deadpool: No Good Deed",
    video: false,
    vote_average: 7.1,
    vote_count: 484,
  },
  {
    adult: false,
    backdrop_path: "/wsgni4E1UnBuvFouUUanSdniQi0.jpg",
    genre_ids: [28, 12, 18],
    id: 718821,
    original_language: "en",
    original_title: "Twisters",
    overview:
      "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
    popularity: 485.383,
    poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
    release_date: "2024-07-10",
    title: "Twisters",
    video: false,
    vote_average: 7.202,
    vote_count: 282,
  },
];
