export const comedyMovies = [
  {
    adult: false,
    backdrop_path: "/A4JG9mkAjOQ3XNJy2oji1Jr224R.jpg",
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    popularity: 14152.827,
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    release_date: "2024-07-24",
    title: "Deadpool & Wolverine",
    video: false,
    vote_average: 8.015,
    vote_count: 994,
  },
  {
    adult: false,
    backdrop_path: "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
    genre_ids: [28, 80, 53, 35],
    id: 573435,
    original_language: "en",
    original_title: "Bad Boys: Ride or Die",
    overview:
      "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
    popularity: 4694.756,
    poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
    release_date: "2024-06-05",
    title: "Bad Boys: Ride or Die",
    video: false,
    vote_average: 7.7,
    vote_count: 1206,
  },
  {
    adult: false,
    backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 1022789,
    original_language: "en",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    popularity: 3406.362,
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    release_date: "2024-06-11",
    title: "Inside Out 2",
    video: false,
    vote_average: 7.6,
    vote_count: 2183,
  },
  {
    adult: false,
    backdrop_path: "/5g2n3ilC8DpYv4diJeuQ1vKG2Kb.jpg",
    genre_ids: [16, 10751, 35, 28],
    id: 519182,
    original_language: "en",
    original_title: "Despicable Me 4",
    overview:
      "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    popularity: 2736.441,
    poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    release_date: "2024-06-20",
    title: "Despicable Me 4",
    video: false,
    vote_average: 7.2,
    vote_count: 477,
  },
  {
    adult: false,
    backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
    genre_ids: [28, 12, 35],
    id: 293660,
    original_language: "en",
    original_title: "Deadpool",
    overview:
      "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
    popularity: 1045.895,
    poster_path: "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
    release_date: "2016-02-09",
    title: "Deadpool",
    video: false,
    vote_average: 7.619,
    vote_count: 30332,
  },
  {
    adult: false,
    backdrop_path: "/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg",
    genre_ids: [16, 35, 10751, 12],
    id: 748783,
    original_language: "en",
    original_title: "The Garfield Movie",
    overview:
      "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
    popularity: 1343.036,
    poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg",
    release_date: "2024-04-30",
    title: "The Garfield Movie",
    video: false,
    vote_average: 7.2,
    vote_count: 631,
  },
  {
    adult: false,
    backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
    genre_ids: [28, 35],
    id: 1048241,
    original_language: "en",
    original_title: "My Spy The Eternal City",
    overview:
      "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
    popularity: 979.672,
    poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
    release_date: "2024-07-18",
    title: "My Spy The Eternal City",
    video: false,
    vote_average: 6.75,
    vote_count: 166,
  },
  {
    adult: false,
    backdrop_path: "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
    genre_ids: [14, 12, 10751, 35],
    id: 974262,
    original_language: "en",
    original_title: "Descendants: The Rise of Red",
    overview:
      "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
    popularity: 921.632,
    poster_path: "/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg",
    release_date: "2024-07-11",
    title: "Descendants: The Rise of Red",
    video: false,
    vote_average: 7.023,
    vote_count: 215,
  },
  {
    adult: false,
    backdrop_path: "/s5znBQmprDJJ553IMQfwEVlfroH.jpg",
    genre_ids: [28, 35, 10752, 18],
    id: 799583,
    original_language: "en",
    original_title: "The Ministry of Ungentlemanly Warfare",
    overview:
      "During World War II, the British Army assigns a group of competent soldiers to carry out a mission against the Nazi forces behind enemy lines... A true story about a secret British WWII organization – the Special Operations Executive. Founded by Winston Churchill, their irregular warfare against the Germans helped to change the course of the war, and gave birth to modern black operations.",
    popularity: 1168.768,
    poster_path: "/8aF0iAKH9MJMYAZdi0Slg77RYa2.jpg",
    release_date: "2024-04-18",
    title: "The Ministry of Ungentlemanly Warfare",
    video: false,
    vote_average: 7.198,
    vote_count: 612,
  },
  {
    adult: false,
    backdrop_path: "/3P52oz9HPQWxcwHOwxtyrVV1LKi.jpg",
    genre_ids: [28, 35, 12],
    id: 383498,
    original_language: "en",
    original_title: "Deadpool 2",
    overview:
      "Wisecracking mercenary Deadpool battles the evil and powerful Cable and other bad guys to save a boy's life.",
    popularity: 758.63,
    poster_path: "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
    release_date: "2018-05-10",
    title: "Deadpool 2",
    video: false,
    vote_average: 7.5,
    vote_count: 17393,
  },
  {
    adult: false,
    backdrop_path: "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
    genre_ids: [28, 35, 80],
    id: 280180,
    original_language: "en",
    original_title: "Beverly Hills Cop: Axel F",
    overview:
      "Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.",
    popularity: 543.672,
    poster_path: "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
    release_date: "2024-06-20",
    title: "Beverly Hills Cop: Axel F",
    video: false,
    vote_average: 6.872,
    vote_count: 756,
  },
  {
    adult: false,
    backdrop_path: "/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg",
    genre_ids: [16, 10751, 12, 18, 35],
    id: 150540,
    original_language: "en",
    original_title: "Inside Out",
    overview:
      "When 11-year-old Riley moves to a new city, her Emotions team up to help her through the transition. Joy, Fear, Anger, Disgust and Sadness work together, but when Joy and Sadness get lost, they must journey through unfamiliar places to get back home.",
    popularity: 511.051,
    poster_path: "/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
    release_date: "2015-06-17",
    title: "Inside Out",
    video: false,
    vote_average: 7.914,
    vote_count: 21339,
  },
  {
    adult: false,
    backdrop_path: "/5ZSwZPKgcTJJwhxjbOHeoBTVaKh.jpg",
    genre_ids: [35, 28, 12],
    id: 567604,
    original_language: "en",
    original_title: "Once Upon a Deadpool",
    overview:
      "A kidnapped Fred Savage is forced to endure Deadpool's PG-13 rendition of Deadpool 2 as a Princess Bride-esque story that's full of magic, wonder & zero F's.",
    popularity: 325.541,
    poster_path: "/5Ka49BWWyKMXr93YMbH5wLN7aAM.jpg",
    release_date: "2018-12-11",
    title: "Once Upon a Deadpool",
    video: false,
    vote_average: 7.093,
    vote_count: 727,
  },
  {
    adult: false,
    backdrop_path: "/gsljBGOjBkbuNt3gvIDXQWnudn.jpg",
    genre_ids: [28, 35, 80],
    id: 558144,
    original_language: "en",
    original_title: "Deadpool: No Good Deed",
    overview:
      "Deadpool sees an opportunity to save the day, but it doesn't go entirely as planned.",
    popularity: 296.578,
    poster_path: "/wlKU9yB0Q8nfPMakBcSBT0JGS7.jpg",
    release_date: "2017-03-03",
    title: "Deadpool: No Good Deed",
    video: false,
    vote_average: 7.1,
    vote_count: 484,
  },
  {
    adult: false,
    backdrop_path: "/w22yUH5pAZ3CcTjbw9GEzPd5wxs.jpg",
    genre_ids: [878, 35],
    id: 1242372,
    original_language: "zh",
    original_title: "从21世纪安全撤离",
    overview:
      'On Planet K, unknown to anyone on Earth, three teenagers chosen by fate can travel back and forth twenty years into the future by sneezing. In the face of a shocking plot to destroy the world, they have nothing but crystal-clear stupidity and single-digit combat power, so how can they transform into heroes and fight against the super-villainous villains who are intent on destroying the world? How can they turn into heroes and fight against the super baddest villains intent on destroying the world? The "King Bomb" brothers, who look like grown-ups but have minds like no other, will save the future on behalf of the K-Star!',
    popularity: 490.973,
    poster_path: "/nZQPbD7IEKWiUDK7s9GKHwqP88g.jpg",
    release_date: "2024-07-18",
    title: "Escape from the 21st Century",
    video: false,
    vote_average: 9.5,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
    genre_ids: [28, 35],
    id: 746036,
    original_language: "en",
    original_title: "The Fall Guy",
    overview:
      "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.",
    popularity: 375.264,
    poster_path: "/tSz1qsmSJon0rqjHBxXZmrotuse.jpg",
    release_date: "2024-04-24",
    title: "The Fall Guy",
    video: false,
    vote_average: 7.2,
    vote_count: 1706,
  },
  {
    adult: false,
    backdrop_path: "/jIka1cO3MIkFwEFJ0ziVhr37avW.jpg",
    genre_ids: [10402, 28, 35],
    id: 1305095,
    original_language: "en",
    original_title: "Deadpool The Musical 2 - Ultimate Disney Parody!",
    overview:
      "Watch as Deadpool sings and slays his way through a series of Disney songs and superhero teams, from The X-Men to The Avengers & more!",
    popularity: 229.25,
    poster_path: "/bcxfS7d5V9a6oojs7CnIZ69tbKs.jpg",
    release_date: "2018-07-10",
    title: "Deadpool The Musical 2 - Ultimate Disney Parody!",
    video: false,
    vote_average: 9.5,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/jt86ZDWeo5SuSryi3kzaysf1CWU.jpg",
    genre_ids: [16, 12, 35, 28, 10751],
    id: 931405,
    original_language: "zh",
    original_title: "小虎墩大英雄",
    overview:
      "The film follows a young boy who sets out on a mission to try and track down his long lost parents.",
    popularity: 334.366,
    poster_path: "/73PZdKGTj2PkIeBfRhTG5KJBY5X.jpg",
    release_date: "2022-02-01",
    title: "Run, Tiger Run!",
    video: false,
    vote_average: 8.077,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: "/nxxCPRGTzxUH8SFMrIsvMmdxHti.jpg",
    genre_ids: [35, 14, 10751],
    id: 639720,
    original_language: "en",
    original_title: "IF",
    overview:
      "A young girl who goes through a difficult experience begins to see everyone's imaginary friends who have been left behind as their real-life friends have grown up.",
    popularity: 285.484,
    poster_path: "/xbKFv4KF3sVYuWKllLlwWDmuZP7.jpg",
    release_date: "2024-05-08",
    title: "IF",
    video: false,
    vote_average: 7.354,
    vote_count: 713,
  },
  {
    adult: false,
    backdrop_path: "/2KGxQFV9Wp1MshPBf8BuqWUgVAz.jpg",
    genre_ids: [16, 28, 12, 35, 10751],
    id: 940551,
    original_language: "en",
    original_title: "Migration",
    overview:
      "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
    popularity: 323.589,
    poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
    release_date: "2023-12-06",
    title: "Migration",
    video: false,
    vote_average: 7.459,
    vote_count: 1587,
  },
];
