export const documentaries = [
  {
    adult: false,
    backdrop_path: "/fRoKZYEFYfWO11uDiQg84Fs7aSt.jpg",
    genre_ids: [99],
    id: 1311546,
    original_language: "fr",
    original_title: "Cérémonie d'ouverture des Jeux Olympiques de Paris 2024",
    overview:
      "On 26 July 2024, the largest-ever Olympic Games Opening Ceremony took place, beginning at 7.30 p.m. CET. The Opening Ceremony of the Olympic Games Paris 2024 was an unprecedented experience drawing on the natural light of the setting sun with all its nuances to illuminate the world’s best athletes as they travelled down the Seine, in the heart of the French capital.",
    popularity: 66.105,
    poster_path: "/mDU7bwWaxeDJyUGyBU4P0I6TgEm.jpg",
    release_date: "2024-07-26",
    title: "Paris 2024 Olympic Opening Ceremony",
    video: false,
    vote_average: 4.774,
    vote_count: 62,
  },
  {
    adult: false,
    backdrop_path: "/b2knUbiZdJ5aQDSYszqI8PvKnb9.jpg",
    genre_ids: [99, 18],
    id: 1268818,
    original_language: "en",
    original_title: "Emma és Eddie: A képen kívül",
    overview:
      "Emma and Eddie live two lives: one on social media and one in real life. The webcam couple is out to save their marriage by starting their own adult web-studio in Eastern Europe.",
    popularity: 55.933,
    poster_path: "/feVCjER9R2bU8qflI3DEPH2oE80.jpg",
    release_date: "2024-04-25",
    title: "Emma and Eddie: A Working Couple",
    video: false,
    vote_average: 4.357,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/sMree7qOX4OuOtTb97yMeUggeAH.jpg",
    genre_ids: [18, 99, 36],
    id: 1108958,
    original_language: "es",
    original_title: "La sirvienta",
    overview:
      "Domestic service worker Lera is accused of a crime. In a cell in the premises of a Civil Guard barracks, she meets Mihaela and Julia, two prostitutes with whom she shares the story of Santa Vicenta María, founder of the Religious of Mary Immaculate, which she says saved her life.",
    popularity: 60.479,
    poster_path: "/8DuhchJlvKyT08peLDSLE8ed8Oi.jpg",
    release_date: "2023-03-24",
    title: "The Servant",
    video: false,
    vote_average: 2,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/1iroQlJdPccnoUi4PGsIRFWPLBV.jpg",
    genre_ids: [99, 10402],
    id: 879805,
    original_language: "en",
    original_title: "I Am: Celine Dion",
    overview:
      "A raw and honest behind-the-scenes look at the iconic superstar's struggle with a life-altering illness. Serving as a love letter to her fans, this inspirational documentary highlights the music that has guided her life while also showcasing the resilience of the human spirit.",
    popularity: 49.287,
    poster_path: "/woznEiocvx8HMYKB2KloHATrDji.jpg",
    release_date: "2024-06-18",
    title: "I Am: Celine Dion",
    video: false,
    vote_average: 8,
    vote_count: 84,
  },
  {
    adult: false,
    backdrop_path: "/bV7eAcBrYb57PwjpQ2ODT6VyFPd.jpg",
    genre_ids: [99],
    id: 318256,
    original_language: "en",
    original_title: "Hot Girls Wanted",
    overview:
      "A first-ever look at the realities of the professional “amateur” porn world and the steady stream of 18-to-19-year old girls entering into it.",
    popularity: 44.769,
    poster_path: "/75ot83QOkc02vujyzmIbumQCU6Y.jpg",
    release_date: "2015-05-29",
    title: "Hot Girls Wanted",
    video: false,
    vote_average: 6.031,
    vote_count: 636,
  },
  {
    adult: false,
    backdrop_path: "/8rft8A9nH43IReybFtYt21ezfMK.jpg",
    genre_ids: [99],
    id: 899082,
    original_language: "en",
    original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    popularity: 54.278,
    poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    release_date: "2022-01-01",
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    video: false,
    vote_average: 7.309,
    vote_count: 3242,
  },
  {
    adult: false,
    backdrop_path: "/5z0rFwwX4wmyOCaEUA4fmnwt1QD.jpg",
    genre_ids: [99, 80],
    id: 1318668,
    original_language: "es",
    original_title: "500 Días de Escobar: la vertiginosa caída del capo",
    overview:
      "The 500-day manhunt for Colombia's Pablo Escobar is detailed through interviews and archival images in this crime documentary.",
    popularity: 62.098,
    poster_path: "/AoEl04jghs9APnpBKzDg37nZQnc.jpg",
    release_date: "2023-12-03",
    title: "500 Days of Escobar",
    video: false,
    vote_average: 9,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/eca3tlO1vtnua8LUK70ISDMYcwF.jpg",
    genre_ids: [99],
    id: 1146302,
    original_language: "en",
    original_title: "Sly",
    overview:
      "His love of film began as an escape from a rocky childhood. From underdog to Hollywood legend, Sylvester Stallone tells his story in this documentary.",
    popularity: 32.684,
    poster_path: "/1utWajLPvv1R9ZwkD98s2ZEngS.jpg",
    release_date: "2023-09-16",
    title: "Sly",
    video: false,
    vote_average: 7.219,
    vote_count: 155,
  },
  {
    adult: false,
    backdrop_path: "/tU3mnpFLOAp2Ia6vHvGIw8ewJQb.jpg",
    genre_ids: [10402, 99],
    id: 1041513,
    original_language: "en",
    original_title: "Encanto at the Hollywood Bowl",
    overview:
      "A taped performance of the Encanto Live-to-Film Concert Experience at the Hollywood Bowl. The original cast puts on a miracle of a concert as they sing the favorite songs, accompanied by a full orchestra and 50 person ensemble, and the Hollywood Bowl transforms into Casita!",
    popularity: 51.126,
    poster_path: "/sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
    release_date: "2022-12-28",
    title: "Encanto at the Hollywood Bowl",
    video: false,
    vote_average: 7.075,
    vote_count: 154,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 447399,
    original_language: "en",
    original_title: "X-Men: The Mutant Watch",
    overview:
      "While Senator Kelly addresses a senate committee about the supposed mutant menace, we learn about the making of the movie, X-Men.",
    popularity: 56.366,
    poster_path: "/vF02RqXLgtmpJM5CRLSuvN3fVHi.jpg",
    release_date: "2000-07-02",
    title: "X-Men: The Mutant Watch",
    video: false,
    vote_average: 6.974,
    vote_count: 208,
  },
  {
    adult: false,
    backdrop_path: "/3gw6ZMxVbfOQcQahGsmwdvFJPOa.jpg",
    genre_ids: [99],
    id: 324558,
    original_language: "en",
    original_title: "X-Rated: The Greatest Adult Movies of All Time",
    overview:
      "The evolution of adult cinema through the most influential films in history, a journey that begins in the 1970s and ends nowadays. An in-depth analysis of the success of the most prestigious erotic films, their impact on industry and society, and their influence on cinema and contemporary culture.",
    popularity: 55.221,
    poster_path: "/1UgdqTHgwNivULiZvNcJ0Mj3skl.jpg",
    release_date: "2015-02-06",
    title: "X-Rated: The Greatest Adult Movies of All Time",
    video: false,
    vote_average: 6.417,
    vote_count: 180,
  },
  {
    adult: false,
    backdrop_path: "/60qVuzQOKgyD57tsgBceT5ScCSX.jpg",
    genre_ids: [99, 10749, 53],
    id: 1214488,
    original_language: "en",
    original_title: "Skywalkers: A Love Story",
    overview:
      "Two real-life daredevils test the limits of their love and trust by illegally scaling one of the world's tallest buildings to perform an acrobatic stunt.",
    popularity: 29.98,
    poster_path: "/7A4x0D1gNTpmMn9E9BW9hWiaOkv.jpg",
    release_date: "2024-07-12",
    title: "Skywalkers: A Love Story",
    video: false,
    vote_average: 7.23,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: "/yEBBtk1eyZltGgJt8Z2zi3KIvvX.jpg",
    genre_ids: [99],
    id: 689249,
    original_language: "es",
    original_title: "La Casa de Papel: el fenómeno",
    overview:
      "A documentary on why 'Money Heist' sparked a wave of enthusiasm around the world for a lovable group of thieves and their professor.",
    popularity: 27.142,
    poster_path: "/AboUXTrDWEi0PuZUqaft0iwBTm7.jpg",
    release_date: "2020-04-03",
    title: "Money Heist: The Phenomenon",
    video: false,
    vote_average: 7.451,
    vote_count: 1059,
  },
  {
    adult: false,
    backdrop_path: "/w4uYP6ebNaLQIjsHcjQhjz3BB2m.jpg",
    genre_ids: [99],
    id: 451995,
    original_language: "fr",
    original_title: "Visages, villages",
    overview:
      "Director Agnès Varda and photographer/muralist JR journey through rural France and form an unlikely friendship.",
    popularity: 26.59,
    poster_path: "/1NX6NTj9FiiJwEgRUmEifSzE7Na.jpg",
    release_date: "2017-06-28",
    title: "Faces Places",
    video: false,
    vote_average: 7.678,
    vote_count: 369,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 737043,
    original_language: "en",
    original_title: "Swingers",
    overview:
      "Observational documentary unlocking the doors of Britain's hidden swinging scene via access to one of the country's most popular swinging clubs and candid interviews with the club's founder, staff and clientele.",
    popularity: 38.443,
    poster_path: "/z4uwQVm0Th3lngECVZvMHVaaFur.jpg",
    release_date: "2020-08-24",
    title: "Swingers",
    video: false,
    vote_average: 4.5,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/1aBRILIlhTTmgbLW7x8X2lf5lxG.jpg",
    genre_ids: [10402, 99],
    id: 1307028,
    original_language: "ko",
    original_title: "블랙핑크 월드투어 [본 핑크] 인 시네마",
    overview:
      "BLACKPINK’s BORN PINK tour that captivated the world comes to the big screen, celebrating the group’s 8th anniversary since their debut!  Drawing an audience of 1.8 million and breaking global records for female group concert tours, experience the energy of the live performances in cinemas worldwide!",
    popularity: 53.699,
    poster_path: "/hWua2arTOzw56tdgbB9hPmU0hE1.jpg",
    release_date: "2024-07-31",
    title: "BLACKPINK WORLD TOUR [BORN PINK] IN CINEMAS",
    video: false,
    vote_average: 8,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/okUGREWC4LN2TSjFX0AOiNJhzdN.jpg",
    genre_ids: [99],
    id: 965143,
    original_language: "ko",
    original_title: "사이버 지옥: n번방을 무너뜨려라",
    overview:
      "Anonymous and exploitative, a network of online chat rooms ran rampant with sex crimes. The hunt to take down its operators required guts and tenacity.",
    popularity: 35.507,
    poster_path: "/eRlW6yvXHyXPuN0Ea6u6Sc48lGm.jpg",
    release_date: "2022-05-17",
    title: "Cyber Hell: Exposing an Internet Horror",
    video: false,
    vote_average: 7.2,
    vote_count: 82,
  },
  {
    adult: false,
    backdrop_path: "/v4cLAQHgY9pwdX33g9cHaFF1lY9.jpg",
    genre_ids: [99, 36],
    id: 1070032,
    original_language: "en",
    original_title: "Beyond Utopia",
    overview:
      "A courageous pastor uses his underground network to rescue and aid North Korean families as they risk their lives to embrace freedom.",
    popularity: 41.253,
    poster_path: "/fcyCtyXabv0X8TInqoL9yq5DCdb.jpg",
    release_date: "2023-10-23",
    title: "Beyond Utopia",
    video: false,
    vote_average: 8,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: "/2VFUh8spzyNbRNPyncIrFmSwBrd.jpg",
    genre_ids: [99],
    id: 438478,
    original_language: "fr",
    original_title: "Pornocratie: Les nouvelles multinationales du sexe",
    overview:
      "Never before have we watched as much porn as today yet the traditional porn industry is dying. The arrival of web sites showing amateur clips has transformed the way porn is made and consumed. Behind this transformation lies one opaque multinational.",
    popularity: 32.144,
    poster_path: "/kfa1KHSaewjv9sSrrHDdWNdroyv.jpg",
    release_date: "2017-03-12",
    title: "Pornocracy: The New Sex Multinationals",
    video: false,
    vote_average: 6.958,
    vote_count: 48,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [10402, 14, 99],
    id: 1314422,
    original_language: "ko",
    original_title: "하이퍼포커스 : 투모로우바이투게더 브이알 콘서트",
    overview:
      "“HYPERFOCUS : TOMORROW X TOGETHER VR CONCERT” is an immersive virtual reality experience that transports you to a fantastical world where you’ll join Gen Z Icons TOMORROW X TOGETHER’s (TXT) first-ever VR concert. Get ready to embark on a thrilling journey with SOOBIN, YEONJUN, BEOMGYU, TAEHYUN, and HUENINGKAI as they perform their hit songs in breathtaking environments. With HYPERFOCUS, the boundaries between reality and fantasy disappear, bringing you closer to the artists and the music.",
    popularity: 27.842,
    poster_path: "/1FWWCmjHnYjbqAFq2ReeFXMW9sD.jpg",
    release_date: "2024-07-31",
    title: "HYPERFOCUS : TOMORROW X TOGETHER VR CONCERT",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];
