export const horrorMovies = [
  {
    adult: false,
    backdrop_path: "/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg",
    genre_ids: [27, 878, 53],
    id: 762441,
    original_language: "en",
    original_title: "A Quiet Place: Day One",
    overview:
      "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
    popularity: 1899.794,
    poster_path: "/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg",
    release_date: "2024-06-26",
    title: "A Quiet Place: Day One",
    video: false,
    vote_average: 7,
    vote_count: 723,
  },
  {
    adult: false,
    backdrop_path: "/59AJ2w9tKRSbBpnxKfB5UyIg6Jf.jpg",
    genre_ids: [27, 53],
    id: 1010600,
    original_language: "en",
    original_title: "The Strangers: Chapter 1",
    overview:
      "After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.",
    popularity: 593.653,
    poster_path: "/cdFZoQDxLRRWXLB3kxCnc674dBF.jpg",
    release_date: "2024-05-15",
    title: "The Strangers: Chapter 1",
    video: false,
    vote_average: 6,
    vote_count: 239,
  },
  {
    adult: false,
    backdrop_path: "/xKJTWGvheOMMlTHgrjN18KaD9Ra.jpg",
    genre_ids: [27, 53],
    id: 1174618,
    original_language: "en",
    original_title: "Alice in Terrorland",
    overview:
      "A recently bereaved teenage girl goes to live with her aunt in a secluded woodland house, unaware that sinister forces lurk within.",
    popularity: 568.755,
    poster_path: "/5XJGvr8g9jkmN6KUIOQOj2iE6K4.jpg",
    release_date: "2023-12-26",
    title: "Alice in Terrorland",
    video: false,
    vote_average: 6.079,
    vote_count: 114,
  },
  {
    adult: false,
    backdrop_path: "/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg",
    genre_ids: [27, 53],
    id: 646683,
    original_language: "en",
    original_title: "The Exorcism",
    overview:
      "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
    popularity: 579.436,
    poster_path: "/ar2h87jlTfMlrDZefR3VFz1SfgH.jpg",
    release_date: "2024-05-30",
    title: "The Exorcism",
    video: false,
    vote_average: 4.571,
    vote_count: 92,
  },
  {
    adult: false,
    backdrop_path: "/iwkWvcXcP8M4r9HLglhVEhgGyVu.jpg",
    genre_ids: [28, 18, 27, 53],
    id: 1001311,
    original_language: "fr",
    original_title: "Sous la Seine",
    overview:
      "In order to save Paris from an international bloodbath, a grieving scientist is forced to face her tragic past when a giant shark appears in the Seine.",
    popularity: 450.659,
    poster_path: "/qZPLK5ktRKa3CL4sKRZtj8UlPYc.jpg",
    release_date: "2024-06-04",
    title: "Under Paris",
    video: false,
    vote_average: 6.097,
    vote_count: 969,
  },
  {
    adult: false,
    backdrop_path: "/716FGefV5R7drdoCOjJtzbPyyY8.jpg",
    genre_ids: [27],
    id: 1207898,
    original_language: "en",
    original_title: "The Jack in the Box: Rises",
    overview:
      "When a creepy Jack-in-the-Box is discovered and opened on the grounds of an exclusive girls' school, six brave students soon enter a fight to the finish against the unleashed demon.",
    popularity: 351.22,
    poster_path: "/oDVjlCTSyF6Fh8Fpm683MyGGnSG.jpg",
    release_date: "2024-01-18",
    title: "The Jack in the Box: Rises",
    video: false,
    vote_average: 6.842,
    vote_count: 73,
  },
  {
    adult: false,
    backdrop_path: "/dbtGinhWWKgQLQ0hjZHMFWxBJcJ.jpg",
    genre_ids: [28, 878, 27, 53],
    id: 1159518,
    original_language: "en",
    original_title: "Black Noise",
    overview:
      "Members of an elite security team deployed to rescue a VIP on an exclusive island.The rescue mission becomes a desperate attempt to survive, escape the island and elude the sinister presence that seeks to harm them.",
    popularity: 330.712,
    poster_path: "/snKpXexv5dtWqEKEmXrJtp8QGQC.jpg",
    release_date: "2023-11-03",
    title: "Black Noise",
    video: false,
    vote_average: 5.211,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/buawWBeKYjYfeiPoS2jIcjOrghZ.jpg",
    genre_ids: [27, 53],
    id: 1214509,
    original_language: "en",
    original_title: "In a Violent Nature",
    overview:
      "The enigmatic resurrection, rampage, and retribution of an undead monster in a remote wilderness unleashes an iconic new killer after a locket is removed from a collapsed fire tower that entombed its rotting corpse.",
    popularity: 288.766,
    poster_path: "/hPfWHgq07nXbeldwEGxWB4JqwtE.jpg",
    release_date: "2024-05-31",
    title: "In a Violent Nature",
    video: false,
    vote_average: 5.82,
    vote_count: 128,
  },
  {
    adult: false,
    backdrop_path: "/fw7NiOxIHq1FWGQCpSW5ZJcbGZR.jpg",
    genre_ids: [27, 53],
    id: 1026819,
    original_language: "en",
    original_title: "The Hunted",
    overview:
      "After their boat capsizes in the Mediterranean Sea, a group of refugees are rescued by rich Europeans who offer them shelter on an idyllic island. But the miracle soon becomes a nightmare when the saviors turn into ruthless manhunters.",
    popularity: 266.322,
    poster_path: "/zgx7I0JfmHbGcbveNk4EK3jFuMk.jpg",
    release_date: "2024-01-18",
    title: "The Hunted",
    video: false,
    vote_average: 6.837,
    vote_count: 44,
  },
  {
    adult: false,
    backdrop_path: "/wXx72bbhhnfORmlSNMWR28fPd8b.jpg",
    genre_ids: [14, 9648, 53, 27],
    id: 1086747,
    original_language: "en",
    original_title: "The Watchers",
    overview:
      "A young artist gets stranded in an extensive, immaculate forest in western Ireland, where, after finding shelter, she becomes trapped alongside three strangers, stalked by mysterious creatures each night.",
    popularity: 248.983,
    poster_path: "/vZVEUPychdvZLrTNwWErr9xZFmu.jpg",
    release_date: "2024-06-06",
    title: "The Watchers",
    video: false,
    vote_average: 6.54,
    vote_count: 593,
  },
  {
    adult: false,
    backdrop_path: "/4woSOUD0equAYzvwhWBHIJDCM88.jpg",
    genre_ids: [53, 27, 28],
    id: 1096197,
    original_language: "en",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 240.742,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.452,
    vote_count: 847,
  },
  {
    adult: false,
    backdrop_path: "/oavbmL3iddJUmC8nQjL6bLHwAP4.jpg",
    genre_ids: [27],
    id: 719221,
    original_language: "en",
    original_title: "Tarot",
    overview:
      "When a group of friends recklessly violate the sacred rule of Tarot readings, they unknowingly unleash an unspeakable evil trapped within the cursed cards. One by one, they come face to face with fate and end up in a race against death.",
    popularity: 301.572,
    poster_path: "/gAEUXC37vl1SnM7PXsHTF23I2vq.jpg",
    release_date: "2024-05-01",
    title: "Tarot",
    video: false,
    vote_average: 6.719,
    vote_count: 725,
  },
  {
    adult: false,
    backdrop_path: "/cCBVpqqFHavVJofPCTHFfQWTuV2.jpg",
    genre_ids: [27, 9648],
    id: 1130899,
    original_language: "ja",
    original_title: "ミンナのウタ",
    overview:
      "Takashi Shimizu's newest film is about a mysterious cassette tape containing a melody. People who hear this melody gradually begin to hum it themselves and become involved in a mysterious incident. What is the mystery behind this melody ?",
    popularity: 244.882,
    poster_path: "/ziWLHm8xjuG2jQf9iIRC7XZZom8.jpg",
    release_date: "2023-08-11",
    title: "Sana",
    video: false,
    vote_average: 7.13,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: "/oX1tNrdqw7kv564QluIbP9yd47H.jpg",
    genre_ids: [16, 28, 9648, 14, 35, 18, 27],
    id: 444483,
    original_language: "ja",
    original_title: "ヴァッサロード",
    overview:
      "Charley, a cyborg vampire who does the Vatican's dirty work, is the thrall of the local vampire playboy Johnny Rayflo. As the two fight crime—and each other—hilarity, violence and sacrilege ensue! But can Charley resist his own desperate cravings for blood? Find out as the devilish duo go up aginst a childlike vampire princess, a mysterious branch of the Unitarian Church...and one another.",
    popularity: 222.945,
    poster_path: "/vyzS55N83jgDtgMeyYJOD7ppYMz.jpg",
    release_date: "2013-03-15",
    title: "Vassalord.",
    video: false,
    vote_average: 5,
    vote_count: 10,
  },
  {
    adult: false,
    backdrop_path: "/14CUYVEfnen8V3tMrfd71UnwbB4.jpg",
    genre_ids: [27],
    id: 821499,
    original_language: "en",
    original_title: "The Inheritance",
    overview:
      "Billionaire Charles Abernathy, on the eve of his 75th birthday, invites his four estranged children back home out of fear that tonight someone – or something – is coming to kill him. To ensure his family will help protect him from whatever’s coming, Abernathy puts each of their inheritances on the line – they’ll get nothing if he’s found dead by dawn.",
    popularity: 220.881,
    poster_path: "/3qQok7BPKVcM0DA9Zu5OeMzzmk6.jpg",
    release_date: "2024-07-12",
    title: "The Inheritance",
    video: false,
    vote_average: 5.8,
    vote_count: 16,
  },
  {
    adult: false,
    backdrop_path: "/tkHQ7tnYYUEnqlrKuhufIsSVToU.jpg",
    genre_ids: [27],
    id: 437342,
    original_language: "en",
    original_title: "The First Omen",
    overview:
      "When a young American woman is sent to Rome to begin a life of service to the church, she encounters a darkness that causes her to question her own faith and uncovers a terrifying conspiracy that hopes to bring about the birth of evil incarnate.",
    popularity: 203.207,
    poster_path: "/uGyiewQnDHPuiHN9V4k2t9QBPnh.jpg",
    release_date: "2024-04-03",
    title: "The First Omen",
    video: false,
    vote_average: 6.891,
    vote_count: 707,
  },
  {
    adult: false,
    backdrop_path: "/roYyPiQDQKmIKUEhO912693tSja.jpg",
    genre_ids: [27, 18, 878],
    id: 447332,
    original_language: "en",
    original_title: "A Quiet Place",
    overview:
      "A family is forced to live in silence while hiding from creatures that hunt by sound.",
    popularity: 304.876,
    poster_path: "/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    release_date: "2018-04-03",
    title: "A Quiet Place",
    video: false,
    vote_average: 7.4,
    vote_count: 13851,
  },
  {
    adult: false,
    backdrop_path: "/5Eip60UDiPLASyKjmHPMruggTc4.jpg",
    genre_ids: [27, 9648, 53],
    id: 1041613,
    original_language: "en",
    original_title: "Immaculate",
    overview:
      "An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.",
    popularity: 206.857,
    poster_path: "/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg",
    release_date: "2024-03-20",
    title: "Immaculate",
    video: false,
    vote_average: 6.368,
    vote_count: 811,
  },
  {
    adult: false,
    backdrop_path: "/AsqUSUqXrK8JfH8WEQnCXVbIAv6.jpg",
    genre_ids: [878, 53, 27],
    id: 520763,
    original_language: "en",
    original_title: "A Quiet Place Part II",
    overview:
      "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path.",
    popularity: 249.26,
    poster_path: "/4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg",
    release_date: "2021-05-21",
    title: "A Quiet Place Part II",
    video: false,
    vote_average: 7.5,
    vote_count: 6293,
  },
  {
    adult: false,
    backdrop_path: "/juhNBu3B3B4ijVimeiUlAHFlooA.jpg",
    genre_ids: [9648, 27, 53],
    id: 1070535,
    original_language: "sv",
    original_title: "Canceled",
    overview:
      "Gone Ghosting is a popular ghost hunting team that earned millions from live broadcasts and selling merch. Lise, Catta, Sandro, and Polly join the group to live-stream a ghost hunt to prove that everything is real. They break into a place where legend says everyone has died and do the craziest broadcast ever live.",
    popularity: 198.782,
    poster_path: "/kgtDMp1Qut4M92g2yTdX2YL9zh8.jpg",
    release_date: "2023-08-25",
    title: "Canceled",
    video: false,
    vote_average: 4.7,
    vote_count: 8,
  },
];
