export const romanceMovies = [
  {
    adult: false,
    backdrop_path: "/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg",
    genre_ids: [18, 10749],
    id: 1010581,
    original_language: "es",
    original_title: "Culpa mía",
    overview:
      "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
    popularity: 342.796,
    poster_path: "/w46Vw536HwNnEzOa7J24YH9DPRS.jpg",
    release_date: "2023-06-08",
    title: "My Fault",
    video: false,
    vote_average: 7.968,
    vote_count: 2746,
  },
  {
    adult: false,
    backdrop_path: "/adAJDB2Au3x5ve2YyWaEYy4EUw.jpg",
    genre_ids: [18, 10749, 35],
    id: 1191610,
    original_language: "es",
    original_title: "Goyo",
    overview:
      "A young autistic museum guide lives by a strict routine — until he falls in love with his coworker and must confront a whirlwind of new, intense emotions.",
    popularity: 347.628,
    poster_path: "/fCjC1RRbEJUpDjM55RNUMXQen0b.jpg",
    release_date: "2024-06-27",
    title: "Goyo",
    video: false,
    vote_average: 6.813,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: "/6YInbRTk39ckuLYFmUgBCKcKNjb.jpg",
    genre_ids: [16, 35, 10751, 14, 10749],
    id: 976573,
    original_language: "en",
    original_title: "Elemental",
    overview:
      "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
    popularity: 194.019,
    poster_path: "/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
    release_date: "2023-06-14",
    title: "Elemental",
    video: false,
    vote_average: 7.655,
    vote_count: 4238,
  },
  {
    adult: false,
    backdrop_path: "/psheU3eQROaYZ0HCbZ0QdbqsiWq.jpg",
    genre_ids: [10749, 878, 18],
    id: 914206,
    original_language: "fr",
    original_title: "La Bête",
    overview:
      "In the near future where emotions have become a threat, Gabrielle finally decides to purify her DNA in a machine that will immerse her in her past lives and rid her of any strong feelings. She then meets Louis and feels a powerful connection, as if she had known him forever.",
    popularity: 303.443,
    poster_path: "/o42BrPukzRXlDi9KBCdClNqhlEr.jpg",
    release_date: "2024-02-07",
    title: "The Beast",
    video: false,
    vote_average: 6.3,
    vote_count: 70,
  },
  {
    adult: false,
    backdrop_path: "/j9eOeLlTGoHoM8BNUJVNyWmIvCi.jpg",
    genre_ids: [10749, 35],
    id: 1072790,
    original_language: "en",
    original_title: "Anyone But You",
    overview:
      "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
    popularity: 167.098,
    poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
    release_date: "2023-12-21",
    title: "Anyone But You",
    video: false,
    vote_average: 7,
    vote_count: 1795,
  },
  {
    adult: false,
    backdrop_path: "/peE1ax04MnTQ9ChDryoDNF95r5.jpg",
    genre_ids: [10749, 35, 10402],
    id: 1255350,
    original_language: "en",
    original_title: "Find Me Falling",
    overview:
      "After a failed comeback album, a rock star retreats to a cliffside home on Cyprus, only to find his new life complicated by visitors — and an old flame.",
    popularity: 200.333,
    poster_path: "/pMWpIPJgL4lYNKxSVMRDFWITeMW.jpg",
    release_date: "2024-07-18",
    title: "Find Me Falling",
    video: false,
    vote_average: 6.483,
    vote_count: 58,
  },
  {
    adult: false,
    backdrop_path: "/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg",
    genre_ids: [80, 10749, 53],
    id: 948549,
    original_language: "en",
    original_title: "Love Lies Bleeding",
    overview:
      "Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.",
    popularity: 179.586,
    poster_path: "/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg",
    release_date: "2024-03-08",
    title: "Love Lies Bleeding",
    video: false,
    vote_average: 6.571,
    vote_count: 390,
  },
  {
    adult: false,
    backdrop_path: "/77Fqz6PFCSnWySDOmEL6ZPcaYIl.jpg",
    genre_ids: [10749, 35],
    id: 1014590,
    original_language: "en",
    original_title: "Upgraded",
    overview:
      "Ana is an ambitious intern dreaming of a career in the art world while trying to impress her demanding boss Claire. When she's upgraded to first class on a work trip, she meets handsome Will, who mistakes Ana for her boss– a white lie that sets off a glamorous chain of events, romance and opportunity, until her fib threatens to surface.",
    popularity: 221.006,
    poster_path: "/4fKjh7zJrlAcZfIfNQCDvvrT5vN.jpg",
    release_date: "2024-02-07",
    title: "Upgraded",
    video: false,
    vote_average: 7.292,
    vote_count: 732,
  },
  {
    adult: false,
    backdrop_path: "/sI6uCeF8mUlZx22mFfHSi9W3XQ9.jpg",
    genre_ids: [10749, 18],
    id: 843527,
    original_language: "en",
    original_title: "The Idea of You",
    overview:
      "40-year-old single mom Solène begins an unexpected romance with 24-year-old Hayes Campbell, the lead singer of August Moon, the hottest boy band on the planet. As they begin a whirlwind romance, it isn't long before Hayes' superstar status poses unavoidable challenges to their relationship, and Solène soon discovers that life in the glare of his spotlight might be more than she bargained for.",
    popularity: 149.724,
    poster_path: "/Y5P4Q3q8nrruZ9aD3wXeJS2Plg.jpg",
    release_date: "2024-05-02",
    title: "The Idea of You",
    video: false,
    vote_average: 7.387,
    vote_count: 1199,
  },
  {
    adult: false,
    backdrop_path: "/sDH1LkdFOkQmTJaF1sIIniQyFOk.jpg",
    genre_ids: [18, 10749],
    id: 597,
    original_language: "en",
    original_title: "Titanic",
    overview:
      "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
    popularity: 181.279,
    poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    release_date: "1997-11-18",
    title: "Titanic",
    video: false,
    vote_average: 7.906,
    vote_count: 24903,
  },
  {
    adult: false,
    backdrop_path: "/jiGoKuVsKzF3isEY1MEDR90Eh1l.jpg",
    genre_ids: [35, 10749],
    id: 1019411,
    original_language: "en",
    original_title: "Space Cadet",
    overview:
      'Tiffany "Rex" Simpson has always dreamed of going to space, and her "doctored" application lands her in NASA\'s ultra-competitive astronaut training program. In over her head, can this Florida girl rely on her quick wits, moxie and determination to get through training and into the cosmos before she blows her cover?',
    popularity: 175.33,
    poster_path: "/7rda0SRuIGA8BDC8FTYHAOyXaRj.jpg",
    release_date: "2024-07-04",
    title: "Space Cadet",
    video: false,
    vote_average: 5.24,
    vote_count: 146,
  },
  {
    adult: false,
    backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
    genre_ids: [10749, 18],
    id: 937287,
    original_language: "en",
    original_title: "Challengers",
    overview:
      'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
    popularity: 116.531,
    poster_path: "/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
    release_date: "2024-04-18",
    title: "Challengers",
    video: false,
    vote_average: 7.2,
    vote_count: 1185,
  },
  {
    adult: false,
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [16, 10749, 18],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 136.962,
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.488,
    vote_count: 11143,
  },
  {
    adult: false,
    backdrop_path: "/5uIttXZuJ1g3eXJ6yc3Obrd3G3a.jpg",
    genre_ids: [878, 10749, 35],
    id: 792307,
    original_language: "en",
    original_title: "Poor Things",
    overview:
      "Brought back to life by an unorthodox scientist, a young woman runs off with a lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
    popularity: 147.952,
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    release_date: "2023-12-07",
    title: "Poor Things",
    video: false,
    vote_average: 7.778,
    vote_count: 3725,
  },
  {
    adult: false,
    backdrop_path: "/b5mzCMHZJJ0I1vlzyglAnk8j2uL.jpg",
    genre_ids: [10749, 18, 35],
    id: 1016121,
    original_language: "en",
    original_title: "Beautiful Disaster",
    overview:
      "Bad-boy Travis is exactly what college freshman Abby needs and wants to avoid. He spends his nights fighting in underground boxing matches, and his days as the ultimate college campus charmer. But Abby wants nothing to do with Travis. Intrigued by Abby’s resistance, Travis offers her a simple bet: if he loses his next fight, he must remain sex-free for a month. If he wins, Abby must live in his apartment for the same amount of time. Either way, Travis has no idea that Abby’s dark past is about to emerge, and he may have finally met his match.",
    popularity: 189.082,
    poster_path: "/bwdLflvCcOCRPqb1x13KPuYIzVx.jpg",
    release_date: "2023-04-04",
    title: "Beautiful Disaster",
    video: false,
    vote_average: 6.69,
    vote_count: 714,
  },
  {
    adult: false,
    backdrop_path: "/e3gVl1gnxEFKLTF6pn6KRqUPi9K.jpg",
    genre_ids: [10749, 18],
    id: 1127166,
    original_language: "it",
    original_title: "Fabbricante di lacrime",
    overview:
      "Adopted together after a tough childhood in an orphanage, Nica and Rigel realize that unexpected but irresistible feelings pull them together.",
    popularity: 127.093,
    poster_path: "/uoBHsxSgfc3PQsSn98RfnbePHOy.jpg",
    release_date: "2024-04-03",
    title: "The Tearsmith",
    video: false,
    vote_average: 6.6,
    vote_count: 666,
  },
  {
    adult: false,
    backdrop_path: "/24r8W0t5ZR9FYF5MvtzFeUa2gmL.jpg",
    genre_ids: [10749, 18],
    id: 1291559,
    original_language: "ja",
    original_title: "余命一年の僕が、余命半年の君と出会った話。",
    overview:
      "With only a year left to live, 17-year-old Akito finds new meaning in life by bringing joy to a terminally ill girl who has just six months remaining.",
    popularity: 166.544,
    poster_path: "/173FD4a0rpSF30z4CoWx6qdx8Ry.jpg",
    release_date: "2024-06-26",
    title: "Drawing Closer",
    video: false,
    vote_average: 8.669,
    vote_count: 62,
  },
  {
    adult: false,
    backdrop_path: "/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 185.129,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.475,
    vote_count: 26940,
  },
  {
    adult: false,
    backdrop_path: "/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg",
    genre_ids: [80, 35, 10749],
    id: 974635,
    original_language: "en",
    original_title: "Hit Man",
    overview:
      "A mild-mannered professor moonlighting as a fake hit man in police stings ignites a chain reaction of trouble when he falls for a potential client.",
    popularity: 152.732,
    poster_path: "/5BfcYFhRVlgWLFo4SCkQNsIWzyy.jpg",
    release_date: "2024-05-16",
    title: "Hit Man",
    video: false,
    vote_average: 7,
    vote_count: 603,
  },
  {
    adult: false,
    backdrop_path: "/zBG5Mg29NH9xxpWMMG7BIvKwYhL.jpg",
    genre_ids: [10749, 18],
    id: 829557,
    original_language: "pl",
    original_title: "365 dni: Ten dzień",
    overview:
      "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
    popularity: 144.337,
    poster_path: "/7qU0SOVcQ8BTJLodcAlulUAG16C.jpg",
    release_date: "2022-04-27",
    title: "365 Days: This Day",
    video: false,
    vote_average: 5.866,
    vote_count: 1443,
  },
];
