export const trendingNow = [
  {
    backdrop_path: "/A4JG9mkAjOQ3XNJy2oji1Jr224R.jpg",
    id: 533535,
    title: "Deadpool & Wolverine",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 35, 878],
    popularity: 14152.827,
    release_date: "2024-07-24",
    video: false,
    vote_average: 8,
    vote_count: 1004,
  },
  {
    backdrop_path: "/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg",
    id: 762441,
    title: "A Quiet Place: Day One",
    original_title: "A Quiet Place: Day One",
    overview:
      "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
    poster_path: "/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [27, 878, 53],
    popularity: 1899.794,
    release_date: "2024-06-26",
    video: false,
    vote_average: 7.043,
    vote_count: 725,
  },
  {
    backdrop_path: "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
    id: 573435,
    title: "Bad Boys: Ride or Die",
    original_title: "Bad Boys: Ride or Die",
    overview:
      "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
    poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 80, 53, 35],
    popularity: 4694.756,
    release_date: "2024-06-05",
    video: false,
    vote_average: 7.659,
    vote_count: 1207,
  },
  {
    backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    id: 94997,
    name: "House of the Dragon",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 18, 10759],
    popularity: 3355.96,
    first_air_date: "2022-08-21",
    vote_average: 8.405,
    vote_count: 4597,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/7cqKGQMnNabzOpi7qaIgZvQ7NGV.jpg",
    id: 76479,
    name: "The Boys",
    original_name: "The Boys",
    overview:
      "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
    poster_path: "/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 10759],
    popularity: 1309.628,
    first_air_date: "2019-07-25",
    vote_average: 8.476,
    vote_count: 10136,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
    id: 1022789,
    title: "Inside Out 2",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [16, 10751, 12, 35],
    popularity: 3406.362,
    release_date: "2024-06-11",
    video: false,
    vote_average: 7.636,
    vote_count: 2186,
  },
  {
    backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    id: 653346,
    title: "Kingdom of the Planet of the Apes",
    original_title: "Kingdom of the Planet of the Apes",
    overview:
      "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [878, 12, 28],
    popularity: 931.197,
    release_date: "2024-05-08",
    video: false,
    vote_average: 7.176,
    vote_count: 2168,
  },
  {
    backdrop_path: "/wsgni4E1UnBuvFouUUanSdniQi0.jpg",
    id: 718821,
    title: "Twisters",
    original_title: "Twisters",
    overview:
      "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
    poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 12, 18],
    popularity: 485.383,
    release_date: "2024-07-10",
    video: false,
    vote_average: 7.2,
    vote_count: 282,
  },
  {
    backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
    id: 786892,
    title: "Furiosa: A Mad Max Saga",
    original_title: "Furiosa: A Mad Max Saga",
    overview:
      "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
    poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 12, 878],
    popularity: 1009.961,
    release_date: "2024-05-22",
    video: false,
    vote_average: 7.6,
    vote_count: 2400,
  },
  {
    backdrop_path: "/s5znBQmprDJJ553IMQfwEVlfroH.jpg",
    id: 799583,
    title: "The Ministry of Ungentlemanly Warfare",
    original_title: "The Ministry of Ungentlemanly Warfare",
    overview:
      "During World War II, the British Army assigns a group of competent soldiers to carry out a mission against the Nazi forces behind enemy lines... A true story about a secret British WWII organization – the Special Operations Executive. Founded by Winston Churchill, their irregular warfare against the Germans helped to change the course of the war, and gave birth to modern black operations.",
    poster_path: "/8aF0iAKH9MJMYAZdi0Slg77RYa2.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 35, 10752, 18],
    popularity: 1168.768,
    release_date: "2024-04-18",
    video: false,
    vote_average: 7.2,
    vote_count: 613,
  },
  {
    backdrop_path: "/5g2n3ilC8DpYv4diJeuQ1vKG2Kb.jpg",
    id: 519182,
    title: "Despicable Me 4",
    original_title: "Despicable Me 4",
    overview:
      "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [16, 10751, 35, 28],
    popularity: 2736.441,
    release_date: "2024-06-20",
    video: false,
    vote_average: 7.207,
    vote_count: 479,
  },
  {
    backdrop_path: "/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg",
    id: 748783,
    title: "The Garfield Movie",
    original_title: "The Garfield Movie",
    overview:
      "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
    poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [16, 35, 10751, 12],
    popularity: 1343.036,
    release_date: "2024-04-30",
    video: false,
    vote_average: 7.217,
    vote_count: 632,
  },
  {
    backdrop_path: "/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg",
    id: 929590,
    title: "Civil War",
    original_title: "Civil War",
    overview:
      "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
    poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [10752, 28, 18],
    popularity: 524.935,
    release_date: "2024-04-10",
    video: false,
    vote_average: 7,
    vote_count: 2032,
  },
  {
    backdrop_path: "/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
    id: 746036,
    title: "The Fall Guy",
    original_title: "The Fall Guy",
    overview:
      "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.",
    poster_path: "/tSz1qsmSJon0rqjHBxXZmrotuse.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 35],
    popularity: 375.264,
    release_date: "2024-04-24",
    video: false,
    vote_average: 7.2,
    vote_count: 1707,
  },
  {
    backdrop_path: "/AbLzUrHtZ0WbvgYQsD0bMzitYEW.jpg",
    id: 211089,
    name: "Strange Tales Of Tang Dynasty",
    original_name: "唐朝诡事录",
    overview:
      "When the dark evil immortal descends from the heaven, and the mysterious underground ghost palace was revealed, a strange herb named the Black Tea suddenly took Chang'an City by storm. However, no one knows whether it is a healthy medicine or one that could harm people. Cases of missing brides in Chang'an City began occurring one after another, which seems to be inextricably linked to the black tea...  Ling Feng, general of the Jin Wu guards was tasked to investigate these cases. On his journey, he meets his strongest opponent in Su Wu Ming, the disciple of Di Ren Jie. The two of them work together to solve these mysterious cases.",
    poster_path: "/sgv6nwj1TlDDKqxbcUEuds8fqoz.jpg",
    media_type: "tv",
    adult: false,
    original_language: "zh",
    genre_ids: [9648, 80, 10759],
    popularity: 3190.562,
    first_air_date: "2022-09-27",
    vote_average: 8,
    vote_count: 17,
    origin_country: ["CN"],
  },
  {
    backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
    id: 37854,
    name: "One Piece",
    original_name: "ワンピース",
    overview:
      'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
    poster_path: "/e3NBGiAifW9Xt8xD5tpARskjccO.jpg",
    media_type: "tv",
    adult: false,
    original_language: "ja",
    genre_ids: [10759, 35, 16],
    popularity: 196.455,
    first_air_date: "1999-10-20",
    vote_average: 8.719,
    vote_count: 4542,
    origin_country: ["JP"],
  },
  {
    backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
    id: 293660,
    title: "Deadpool",
    original_title: "Deadpool",
    overview:
      "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
    poster_path: "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 12, 35],
    popularity: 1045.895,
    release_date: "2016-02-09",
    video: false,
    vote_average: 7.619,
    vote_count: 30335,
  },
  {
    backdrop_path: "/vX71TGviqLsOtDNJ9q1QR4m14kH.jpg",
    id: 218589,
    name: "Those About to Die",
    original_name: "Those About to Die",
    overview:
      "Within the spectacular, complex and corrupt world of gladiatorial sports in Ancient Rome, follow an ensemble of diverse characters across the many layers of Roman society where sports, politics and business intersect and collide.",
    poster_path: "/gvz0m4MJ8sAj6yMcQdwN07bNjRY.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [18],
    popularity: 485.163,
    first_air_date: "2024-07-18",
    vote_average: 7.848,
    vote_count: 69,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
    id: 1048241,
    title: "My Spy The Eternal City",
    original_title: "My Spy The Eternal City",
    overview:
      "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
    poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
    media_type: "movie",
    adult: false,
    original_language: "en",
    genre_ids: [28, 35],
    popularity: 979.672,
    release_date: "2024-07-18",
    video: false,
    vote_average: 6.75,
    vote_count: 166,
  },
  {
    backdrop_path: "/33Al50uZ9cZSddklcuHTaHmNxeE.jpg",
    id: 114924,
    name: "Time Bandits",
    original_name: "Time Bandits",
    overview:
      "Eleven-year-old Kevin's passion for history is put to the test when he joins a ragtag group of time-traveling thieves on a high-stakes and hilarious adventure.",
    poster_path: "/ahnTuygdAbjXvLKzLQlK2txosMX.jpg",
    media_type: "tv",
    adult: false,
    original_language: "en",
    genre_ids: [10765, 10759, 35],
    popularity: 607.085,
    first_air_date: "2024-07-23",
    vote_average: 5.5,
    vote_count: 26,
    origin_country: ["NZ", "GB", "US"],
  },
];
